CREATE TABLE IF NOT EXISTS zones (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
guild_id VARCHAR(32) NOT NULL,
name VARCHAR(100) NOT NULL,
slug VARCHAR(100) NOT NULL,
owner_user_id VARCHAR(32) NOT NULL,
category_id VARCHAR(32) NOT NULL,
text_panel_id VARCHAR(32) NOT NULL,
text_reception_id VARCHAR(32) NOT NULL,
text_general_id VARCHAR(32) NOT NULL,
text_anon_id VARCHAR(32) NOT NULL,
voice_id VARCHAR(32) NOT NULL,
role_owner_id VARCHAR(32) NOT NULL,
role_member_id VARCHAR(32) NOT NULL,
role_muted_id VARCHAR(32) NULL,
policy ENUM('closed','ask','invite','open') NOT NULL DEFAULT 'closed',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UNIQUE KEY uniq_guild_slug (guild_id, slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zone_members (
zone_id BIGINT UNSIGNED NOT NULL,
user_id VARCHAR(32) NOT NULL,
role ENUM('owner','member') NOT NULL DEFAULT 'member',
PRIMARY KEY(zone_id, user_id),
FOREIGN KEY(zone_id) REFERENCES zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zone_member_roles (
zone_id BIGINT UNSIGNED NOT NULL,
role_id VARCHAR(32) NOT NULL,
user_id VARCHAR(32) NOT NULL,
PRIMARY KEY(zone_id, role_id, user_id),
FOREIGN KEY(zone_id) REFERENCES zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS join_codes (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
zone_id BIGINT UNSIGNED NOT NULL,
issued_to_user_id VARCHAR(32) NOT NULL,
code VARCHAR(64) NOT NULL,
expires_at DATETIME NOT NULL,
used BOOLEAN NOT NULL DEFAULT FALSE,
FOREIGN KEY(zone_id) REFERENCES zones(id) ON DELETE CASCADE,
UNIQUE KEY uniq_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS join_requests (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
zone_id BIGINT UNSIGNED NOT NULL,
applicant_user_id VARCHAR(32) NOT NULL,
status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
message_id VARCHAR(32) NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(zone_id) REFERENCES zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS anon_channels (
zone_id BIGINT UNSIGNED NOT NULL,
source_channel_id VARCHAR(32) NOT NULL,
webhook_id VARCHAR(32) NOT NULL,
webhook_token VARCHAR(255) NOT NULL,
PRIMARY KEY(zone_id),
FOREIGN KEY(zone_id) REFERENCES zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zone_roles (
id INT AUTO_INCREMENT PRIMARY KEY,
zone_id INT NOT NULL,
role_id VARCHAR(20) NOT NULL,
name VARCHAR(64) NOT NULL,
color VARCHAR(7) NULL,
UNIQUE KEY uq_zone_roleid (zone_id, role_id),
INDEX ix_zone (zone_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS anon_logs (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
guild_id VARCHAR(32) NOT NULL,
source_zone_id BIGINT UNSIGNED NOT NULL,
author_id VARCHAR(32) NOT NULL,
content TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
INDEX idx_created_at (created_at),
FOREIGN KEY(source_zone_id) REFERENCES zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS temp_groups (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
category_id VARCHAR(32) NOT NULL,
archived BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
expires_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS temp_group_members (
temp_group_id BIGINT UNSIGNED NOT NULL,
user_id VARCHAR(32) NOT NULL,
PRIMARY KEY(temp_group_id, user_id),
FOREIGN KEY(temp_group_id) REFERENCES temp_groups(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS events (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(120) NOT NULL,
status ENUM('draft','running','ended') NOT NULL DEFAULT 'draft',
starts_at DATETIME NULL,
ends_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_participants (
event_id BIGINT UNSIGNED NOT NULL,
user_id VARCHAR(32) NOT NULL,
zone_id BIGINT UNSIGNED NOT NULL,
joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(event_id, user_id),
FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
FOREIGN KEY(zone_id) REFERENCES zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zone_activity (
zone_id BIGINT UNSIGNED NOT NULL,
day DATE NOT NULL,
msgs INT NOT NULL DEFAULT 0,
reacts INT NOT NULL DEFAULT 0,
voice_minutes INT NOT NULL DEFAULT 0,
event_points INT NOT NULL DEFAULT 0,
PRIMARY KEY(zone_id, day),
FOREIGN KEY(zone_id) REFERENCES zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
guild_id VARCHAR(32) PRIMARY KEY,
anon_admin_channel_id VARCHAR(32) NULL,
requests_channel_id VARCHAR(32) NULL,
events_admin_channel_id VARCHAR(32) NULL,
journal_channel_id VARCHAR(32) NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS panel_messages (
zone_id INT NOT NULL PRIMARY KEY,
members_msg_id VARCHAR(32) NULL,
roles_msg_id VARCHAR(32) NULL,
channels_msg_id VARCHAR(32) NULL,
policy_msg_id VARCHAR(32) NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- TEMP GROUPS V2
ALTER TABLE temp_groups
	ADD COLUMN IF NOT EXISTS text_channel_id VARCHAR(32) NULL,
	ADD COLUMN IF NOT EXISTS voice_channel_id VARCHAR(32) NULL,
	ADD COLUMN IF NOT EXISTS panel_message_id VARCHAR(32) NULL,
	ADD COLUMN IF NOT EXISTS is_open BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS last_activity_at DATETIME NULL,
	ADD COLUMN IF NOT EXISTS frozen_until DATETIME NULL;

ALTER TABLE temp_group_members
	ADD COLUMN IF NOT EXISTS role ENUM('member','spectator') NOT NULL DEFAULT 'member';

CREATE TABLE IF NOT EXISTS temp_group_freeze_votes (
	temp_group_id BIGINT UNSIGNED NOT NULL,
	user_id VARCHAR(32) NOT NULL,
	action ENUM('remove','keep') NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (temp_group_id, user_id, action),
	FOREIGN KEY (temp_group_id) REFERENCES temp_groups(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ANON THRESHOLD
CREATE TABLE IF NOT EXISTS anon_daily_counts (
	guild_id VARCHAR(32) NOT NULL,
	day DATE NOT NULL,
	user_id VARCHAR(32) NOT NULL,
	count INT NOT NULL DEFAULT 0,
	PRIMARY KEY (guild_id, day, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- SETTINGS EXT
ALTER TABLE settings
	ADD COLUMN IF NOT EXISTS staff_announcements_channel_id VARCHAR(32) NULL,
	ADD COLUMN IF NOT EXISTS anon_threshold INT NOT NULL DEFAULT 10;

-- EVENTS EXT
ALTER TABLE events
	ADD COLUMN IF NOT EXISTS author_id VARCHAR(32) NULL,
	ADD COLUMN IF NOT EXISTS game VARCHAR(120) NULL,
	ADD COLUMN IF NOT EXISTS description TEXT NULL,
	ADD COLUMN IF NOT EXISTS max_participants INT NULL,
	ADD COLUMN IF NOT EXISTS temp_group_id BIGINT UNSIGNED NULL,
	ADD COLUMN IF NOT EXISTS scheduled_at DATETIME NULL,
	ADD COLUMN IF NOT EXISTS announce_payload JSON NULL;

CREATE TABLE IF NOT EXISTS event_questions (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	event_id BIGINT UNSIGNED NOT NULL,
	from_user_id VARCHAR(32) NOT NULL,
	to_user_id VARCHAR(32) NOT NULL,
	question TEXT NOT NULL,
	answer TEXT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- END
